ALTER TABLE SMS_COUPON ADD MAIN_ACTIVITY_ID VARCHAR2(32) DEFAULT NULL;
ALTER TABLE SMS_COUPON ADD SUB_ACTIVITY_ID VARCHAR2(32) DEFAULT NULL;
ALTER TABLE SMS_COUPON ADD PREFECTURE_ID NUMBER(20) DEFAULT NULL;

CREATE INDEX IDX_SMS_COUPON_PREFECTURE_ID ON SMS_COUPON(PREFECTURE_ID);

CREATE INDEX IDX_SMS_COUPON_SUB_ACTIVITY_ID ON SMS_COUPON(SUB_ACTIVITY_ID);