ALTER TABLE ODS_SMS_COUPON ADD MAIN_ACTIVITY_ID VARCHAR2(32) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD SUB_ACTIVITY_ID VARCHAR2(32) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD PREFECTURE_ID NUMBER(20) DEFAULT NULL;