COMMENT ON COLUMN PMS_PRODUCT.IDENTIFICATION IS '商品标识：默认0:常规商品 1:达标专属礼';

COMMENT ON COLUMN ODS_PMS_PRODUCT.IDENTIFICATION IS '商品标识：默认0:常规商品 1:达标专属礼';

COMMENT ON COLUMN CMS_PREFECTURE.PREFECTURE_TYPE IS '专区类型：默认0:常规专区 1:达标专区';

COMMENT ON COLUMN SMS_COUPON.MAIN_ACTIVITY_ID IS '主活动id';
COMMENT ON COLUMN SMS_COUPON.SUB_ACTIVITY_ID IS '子活动id';
COMMENT ON COLUMN SMS_COUPON.PREFECTURE_ID IS '专区id';
COMMENT ON COLUMN SMS_COUPON.COUPON_TYPE IS '优惠券类型：0 积分兑换券(自行兑换/行发) 1 指定商品免费兑换券 2 指定商品现金优惠券 4 指定专区现金优惠券 5 全场通用现金优惠券';
COMMENT ON COLUMN SMS_COUPON.BATCH_STATUS IS '批次状态:0 待发放1 已发放2 已过期 3 已作废 4 待生效 5 已生效 6 已失效';

COMMENT ON COLUMN ODS_SMS_COUPON.MAIN_ACTIVITY_ID IS '主活动id';
COMMENT ON COLUMN ODS_SMS_COUPON.SUB_ACTIVITY_ID IS '子活动id';
COMMENT ON COLUMN ODS_SMS_COUPON.PREFECTURE_ID IS '专区id';
COMMENT ON COLUMN ODS_SMS_COUPON.COUPON_TYPE IS '优惠券类型：0 积分兑换券(自行兑换/行发) 1 指定商品免费兑换券 2 指定商品现金优惠券 4 指定专区现金优惠券 5 全场通用现金优惠券';

COMMENT ON COLUMN SMS_USER_COUPON.COUPON_TYPE IS '优惠券类型：0 积分兑换券(自行兑换/行发) 1 指定商品免费兑换券 2 指定商品现金优惠券 4 指定专区现金优惠券 5 全场通用现金优惠券';

COMMENT ON COLUMN ODS_SMS_USER_COUPON.COUPON_TYPE IS '优惠券类型：0 积分兑换券(自行兑换/行发) 1 指定商品免费兑换券 2 指定商品现金优惠券 4 指定专区现金优惠券 5 全场通用现金优惠券';