alter table oms_order add DISCOUNT_AMOUNT NUMBER(8,2);
COMMENT ON COLUMN oms_order.DISCOUNT_AMOUNT IS '优惠金额';

alter table pms_sku_stock add DISCOUNT_AMOUNT NUMBER(8,2);
COMMENT ON COLUMN pms_sku_stock.DISCOUNT_AMOUNT IS '优惠金额';

alter table TRADE_DETAIL_REPORT add DISCOUNT_AMOUNT NUMBER(8,2);
COMMENT ON COLUMN TRADE_DETAIL_REPORT.DISCOUNT_AMOUNT IS '优惠金额';

alter table TRADE_TOTAL_REPORT add DISCOUNT_AMOUNT NUMBER(8,2);
COMMENT ON COLUMN TRADE_TOTAL_REPORT.DISCOUNT_AMOUNT IS '优惠金额';
