ALTER TABLE OMS_ORDER ADD ORDER_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE OMS_ORDER ADD ORDER_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE OMS_ORDER ADD ORDER_PARAM3 VARCHAR2(100) DEFAULT NULL;

CREATE INDEX IDX_OMS_ORDER_USER_COUPON_ID ON OMS_ORDER(USER_COUPON_ID);