ALTER TABLE SMS_USER_COUPON ADD USER_COUPON_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE SMS_USER_COUPON ADD USER_COUPON_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE SMS_USER_COUPON ADD USER_COUPON_PARAM3 VARCHAR2(100) DEFAULT NULL;

CREATE INDEX IDX_SMS_USER_COUPON_BATCH_NO ON SMS_USER_COUPON(BATCH_NO);