ALTER TABLE PMS_SKU_STOCK ADD SKU_STOCK_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE PMS_SKU_STOCK ADD SKU_STOCK_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE PMS_SKU_STOCK ADD SKU_STOCK_PARAM3 VARCHAR2(100) DEFAULT NULL;
