ALTER TABLE ODS_SMS_COUPON ADD REL_COUPON_ID NUMBER(20) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD DISTRIBUTE_WAY NUMBER(1) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD COUPON_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD COUPON_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_SMS_COUPON ADD COUPON_PARAM3 VARCHAR2(100) DEFAULT NULL;
