ALTER TABLE ODS_OMS_ORDER ADD RECHARGE_SEQ VARCHAR2(30) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER ADD RECHARGE_REMARK VARCHAR2(2000) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER ADD ORDER_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER ADD ORDER_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER ADD ORDER_PARAM3 VARCHAR2(100) DEFAULT NULL;
