ALTER TABLE ODS_OMS_ORDER_REFUND ADD ORDER_REFUND_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER_REFUND ADD ORDER_REFUND_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_OMS_ORDER_REFUND ADD ORDER_REFUND_PARAM3 VARCHAR2(100) DEFAULT NULL;
