ALTER TABLE ODS_SMS_USER_COUPON ADD USER_COUPON_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_SMS_USER_COUPON ADD USER_COUPON_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_SMS_USER_COUPON ADD USER_COUPON_PARAM3 VARCHAR2(100) DEFAULT NULL;