ALTER TABLE ODS_PMS_PRODUCT ADD PRODUCT_PARAM1 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_PMS_PRODUCT ADD PRODUCT_PARAM2 VARCHAR2(100) DEFAULT NULL;
ALTER TABLE ODS_PMS_PRODUCT ADD PRODUCT_PARAM3 VARCHAR2(100) DEFAULT NULL;
