COMMENT ON COLUMN SYSTEM_PARAMS_CONFG.PARAM_TYPE IS '参数类型：0 积分值比例配置 1 自动确认收货失效配置 2 退款申请有效期配置 3 物流公司配置 4 客服电话 5 订单参数管理';

COMMENT ON COLUMN SMS_COUPON.REL_COUPON_ID IS '关联积分券商品ID';
COMMENT ON COLUMN SMS_COUPON.DISTRIBUTE_WAY IS '发放方式: 0:用户兑换 1:行方发放';
COMMENT ON COLUMN SMS_COUPON.COUPON_PARAM1 IS '话费';
COMMENT ON COLUMN SMS_COUPON.COUPON_PARAM2 IS '油卡';
COMMENT ON COLUMN SMS_COUPON.COUPON_PARAM3 IS '视频';

COMMENT ON COLUMN OMS_ORDER.ORDER_PARAM1 IS '话费';
COMMENT ON COLUMN OMS_ORDER.ORDER_PARAM2 IS '油卡';
COMMENT ON COLUMN OMS_ORDER.ORDER_PARAM3 IS '视频';

COMMENT ON COLUMN OMS_ORDER_REFUND.ORDER_REFUND_PARAM1 IS '话费';
COMMENT ON COLUMN OMS_ORDER_REFUND.ORDER_REFUND_PARAM2 IS '油卡';
COMMENT ON COLUMN OMS_ORDER_REFUND.ORDER_REFUND_PARAM3 IS '视频';

COMMENT ON COLUMN SMS_USER_COUPON.USER_COUPON_PARAM1 IS '话费';
COMMENT ON COLUMN SMS_USER_COUPON.USER_COUPON_PARAM2 IS '油卡';
COMMENT ON COLUMN SMS_USER_COUPON.USER_COUPON_PARAM3 IS '视频';

COMMENT ON COLUMN PMS_PRODUCT.PRODUCT_PARAM1 IS '话费';
COMMENT ON COLUMN PMS_PRODUCT.PRODUCT_PARAM2 IS '油卡';
COMMENT ON COLUMN PMS_PRODUCT.PRODUCT_PARAM3 IS '视频';

COMMENT ON COLUMN PMS_SKU_STOCK.SKU_STOCK_PARAM1 IS '话费';
COMMENT ON COLUMN PMS_SKU_STOCK.SKU_STOCK_PARAM2 IS '油卡';
COMMENT ON COLUMN PMS_SKU_STOCK.SKU_STOCK_PARAM3 IS '视频';

COMMENT ON COLUMN ODS_SMS_COUPON.REL_COUPON_ID IS '关联积分券商品ID';
COMMENT ON COLUMN ODS_SMS_COUPON.DISTRIBUTE_WAY IS '发放方式: 0:用户兑换 1:行方发放';
COMMENT ON COLUMN ODS_SMS_COUPON.COUPON_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_SMS_COUPON.COUPON_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_SMS_COUPON.COUPON_PARAM3 IS '视频';

COMMENT ON COLUMN ODS_OMS_ORDER.ORDER_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_OMS_ORDER.ORDER_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_OMS_ORDER.ORDER_PARAM3 IS '视频';
COMMENT ON COLUMN ODS_OMS_ORDER.RECHARGE_REMARK IS '充值原因';
COMMENT ON COLUMN ODS_OMS_ORDER.RECHARGE_SEQ IS '充值流水';

COMMENT ON COLUMN ODS_OMS_ORDER_REFUND.ORDER_REFUND_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_OMS_ORDER_REFUND.ORDER_REFUND_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_OMS_ORDER_REFUND.ORDER_REFUND_PARAM3 IS '视频';

COMMENT ON COLUMN ODS_SMS_USER_COUPON.USER_COUPON_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_SMS_USER_COUPON.USER_COUPON_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_SMS_USER_COUPON.USER_COUPON_PARAM3 IS '视频';

COMMENT ON COLUMN ODS_PMS_PRODUCT.PRODUCT_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_PMS_PRODUCT.PRODUCT_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_PMS_PRODUCT.PRODUCT_PARAM3 IS '视频';

COMMENT ON COLUMN ODS_PMS_SKU_STOCK.SKU_STOCK_PARAM1 IS '话费';
COMMENT ON COLUMN ODS_PMS_SKU_STOCK.SKU_STOCK_PARAM2 IS '油卡';
COMMENT ON COLUMN ODS_PMS_SKU_STOCK.SKU_STOCK_PARAM3 IS '视频';