UPDATE SMS_COUPON t SET t.DISTRIBUTE_WAY = 0 WHERE COUPON_TYPE = 0;
UPDATE SMS_COUPON t SET t.DISTRIBUTE_WAY = 1 WHERE COUPON_TYPE = 1;
UPDATE SMS_COUPON t SET t.DISTRIBUTE_WAY = 1 WHERE COUPON_TYPE = 2;

COMMIT;